### ISSUE TITLE
Add support for @Version

### ISSUE THREAD

**Issue by tombentley** [kroxylicious/kroxylicious-junit5-extension#12]
Some providers (e.g. container-based, or possibly forking, but not in-VM)  will be able to support multiple broker versions. We should try to implement this.

**Comment by franvila** [comment]
Isn't this already taken into account on that JIRA ticket? https://issues.redhat.com/browse/MGDSTRM-10128

This points as well to that issue in kroxylicious: https://github.com/kroxylicious/kroxylicious/issues/86
