### ISSUE TITLE
The release of a new native kafka image breaks the build (testVersions fails)

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious-junit5-extension#181]
Good catch @k-wall we should maybe revisit the test so new releases don't just break the build

_Originally posted by @SamBarker in https://github.com/kroxylicious/kroxylicious-junit5-extension/pull/180#pullrequestreview-1633921551_

**Comment by SamBarker** [comment]
Hmm that's a point we do need a canary, but I don't like a magically failing build either...

**Comment by SamBarker** [comment]
OHh maybe we can get the test to assert that only the set of expected versions appears and thus when dependabot opens a PR for the new image it will fail?

**Comment by k-wall** [comment]
> OHh maybe we can get the test to assert that only the set of expected versions appears and thus when dependabot opens a PR for the new image it will fail?

Yes, that's my idea.  The other tests will still use latest.  I'll open a PR.
