### ISSUE TITLE
release script  assumes origin when pushing tags

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious-junit5-extension#200]
The release script uses `git push --tags` to push up the tag to the remote repo.  This only works if your remote origin points at the main repo.  In my case, I have origin pointed at my fork and upstream pointed at the main repo.
 
https://github.com/kroxylicious/kroxylicious-junit5-extension/blob/5b8e75343738ba46d7753aa4a90cad3e948cc986/scripts/release.sh#L74

**Comment by k-wall** [comment]
@SamBarker I ended up having to manually do `git push --tag v0.6.0 upstream` after the release.sh had run. Where do you see the problem here?  I wonder if the script ought to take an argument that allows the upstream to be specified.

**Comment by SamBarker** [comment]
> @SamBarker I ended up having to manually do git push --tag v0.6.0 upstream after the release.sh had run. Where do you see the problem here? I wonder if the script ought to take an argument that allows the upstream to be specified.

Its another drift between the projects. The release script for Kroxylicious itself already supports the idea of which remote to pull from (though it may not leverage it for the push) so yes I think both projects should allow the specification of which remote to use for pulling and pushing tags too.
