### ISSUE TITLE
release script ought to sensibly clean up if it fails.

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious-junit5-extension#201]
**Is your feature request related to a problem? Please describe.**

If the release.sh fails for some reason, the user needs to manually clean up local branches/tags etc and switch working branch.
If you rerun the script fails as it tries to create branches etc that already exist.  This is a bit of a pain.    

**Describe the solution you'd like**

If the script hasn't reached the stage where it is pushed remotely,  it should clean-up - i.e. delete local branches and tags that its created, and reset the working branch back to original state.

**Describe alternatives you've considered**

**Additional context**

**Comment by SamBarker** [comment]
I agree its painful however I'm not sure cleanup on exit is very helpful for debugging issues etc. 

I suspect we want a mechanism to force a reset/clean state on the subsequent run.

**Comment by k-wall** [comment]
I made an improvement as part of #213 that helps.  Git prints the hash of the branches when they are deleted, so you can use that to snoop.
