### ISSUE TITLE
TestcontainersKafkaCluster may use stale latest kafka images

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious-junit5-extension#421]
**Describe the bug**

quay.io/ogunalp/kafka-native's [tagging container scheme](https://quay.io/repository/ogunalp/kafka-native?tab=tags&tag=latest) includes the use of latest floating tags:

* `latest` means the latest image for the latest kafka release known to kafka-native
* `latest-snapshot` mean the latest snapshot created by ogunalp's CI
* `latest-kafka-3.9.0` means the  latest image release supporting Kafka 3.9.0

Kroxylicious Junit Ext defaults to using the latter (`latest-kafka-x.y.z`) with x.y.z based on the version of Kafka in the classpath.  It is possible for the user of the Junit Ext to override this behaviour.

The issue is that the image `latest-kafka-x.x.x` in the user's Docker/Podman cache might be stale.  The Junit Ext does not specify a pull policy, so the Testcontainer defaults are applying.   The upshot is that the the user's code runs with an unexpected image.

We should consider telling Docker to use a Always pull policy when using floating tags such as latest.

**Expected behavior**

**Logs**

Attach or copy and paste relevant logs.

**Additional context**

We might consider doing something like:

```
        KafkaContainer kafkaContainer = new KafkaContainer(kafkaImage)
                .withName(name)
                .withNetwork(network)
                .withImagePullPolicy(kafkaImage.getVersionPart().contains("latest") ? PullPolicy.alwaysPull() : null)
                .withNetworkAliases(netAlias);
```

**Comment by k-wall** [comment]
Workaround:

The user could set pull.policy as env var (or system property) to `org.testcontainers.images.AlwaysPullPolicy` to override Testcontainer's default pull policy.

**Comment by SamBarker** [comment]
Thanks @k-wall I agree we need a better story around pulling kafka native images.

I've taken the liberty of adding the triaged label as this one keeps tripping me up!
