### ISSUE TITLE
API to restart kafka brokers

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/kroxylicious-junit5-extension#86]
Thinking forward about testing Kroxylicious edge cases - network disconnection.

As the author of a component like Kroxylicious, I want to be able to write integration tests that ensure my component correctly handles broker restarts correctly.  To this end I would value an API that permitted me to restart one or more brokers within a cluster.  It is important that the broker comes back on the same ports (as it would in production).  I have this requirement for both the in-VM and container use-case.

I'm imagine a API that looks like:

`#restart(int nodeId)`
or maybe 
`#restart(Set<Integer> nodeId)`

control would return to the caller once the  broker restart is finished and all the brokers see one and other.

I don't envisaged needing functionality to do things like roll the brokers of a cluster (waiting for ISRs etc).  If a test needs that, it could easily construct it itself.

I don't envisage needing the ability to restart any kafka broker that is solely in the kraft controller role.

**Comment by k-wall** [comment]
@SamBarker @racheljpg @devguyio @franvila @robobario  comments/edits welcome..

**Comment by tombentley** [comment]
> all the brokers see one and other.

This is actually tricky to do using the Admin client. You have no control over which brokers get sent the `Metadata`/`DescribeCluster` request, nor do you know for sure that the metadata you receive isn't from before the restart. If might be necessary to observe the broker logging to do this robustly, if you're wedded to this semantic.

**Comment by k-wall** [comment]
@tombentley so the approach that @SamBarker and I landed on was to [create a single partition topic with `RF = <number of brokers>`](https://github.com/kroxylicious/kroxylicious-junit5-extension/blob/864531d765127d425d2d02f9e61961214cf0a5ca/impl/src/main/java/io/kroxylicious/testing/kafka/common/Utils.java#L121) and wait for that to be reported as having replicas on all brokers.   That seems to have stabilized the tests.

**Comment by k-wall** [comment]
@franvila wondering if you'd have capacity to take a look at this?   being able to demonstrate kroxy's robustness will be key to first production use-cases.

**Comment by k-wall** [comment]
I'm picking this feature up.
