### ISSUE TITLE
Simplify createNetwork

### ISSUE THREAD

**Issue by SamBarker** [kroxylicious/kroxylicious-junit5-extension#92]
https://github.com/testcontainers/testcontainers-java/issues/6667 has been resolved we should be able to simplify https://github.com/kroxylicious/kroxylicious-junit5-extension/blob/bf44a8c7c5aa7aa0d86f69d9a44fc503f2b45a5c/impl/src/main/java/io/kroxylicious/testing/kafka/testcontainers/TestcontainersKafkaCluster.java#L278-L292

**Comment by k-wall** [comment]
Thanks for spotting this. I'll put up a PR.
